[package]
name = "toktrie"
version = "0.1.0"
edition = "2021"

[lib]
name = "toktrie"

[dependencies]
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
anyhow = "1.0.75"
bytemuck = "1.16.0"
bytemuck_derive = "1.6.0"
rustc-hash = { version = "2.0.0" }
