name: AICIrt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup target add wasm32-wasi
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Build aici_abi
      run: cargo build --verbose --release
      working-directory: controllers/aici_abi
    - name: Build uppercase
      run: cargo build --verbose --release
      working-directory: controllers/uppercase
    - name: Build pyctrl
      run: cargo build --verbose --release
      working-directory: controllers/pyctrl
    - name: Build jsctrl
      run: cargo build --verbose --release
      working-directory: controllers/jsctrl
    - name: Build declctrl
      run: cargo build --verbose --release
      working-directory: controllers/declctrl
    - name: Build aicirt
      run: cargo build --verbose --release
      working-directory: aicirt
    - name: Release script
      run: ./scripts/release.sh --xz
    - name: Artifact upload
      uses: actions/upload-artifact@v4
      with:
        name: aicirt-xz
        path: target/dist/*.tar.xz
